# Generated by Django 5.2.8 on 2025-11-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('ClassName', models.CharField(max_length=10)),
                ('Section', models.CharField(max_length=1)),
                ('Gender', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Phone', models.CharField(max_length=15)),
                ('City', models.CharField(max_length=50)),
                ('Percentage', models.FloatField()),
                ('Attendance', models.IntegerField()),
            ],
        ),
    ]
